spring:
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: jpro123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true